---
title: "Presidential Candidates in New Hampshire"
author: "Heike Hofmann"
output: html_document
---

```{r, echo=FALSE, fig.width=12, fig.height=10, message=FALSE, warning = FALSE}
library(XML)
library(lubridate)
library(dplyr)
library(stringr)
library(reshape2)
library(ggplot2)
library(RColorBrewer)

source("caucus.R")
###############
#  functions
sub <- function(x, replace=c("--"), by=NA) {
  x <- as.character(x)
  idx <- which(x %in% replace)
  if (length(idx) > 0) x[idx] <- by
  x
}

fixYear <- function(date) {
  month <- month(date)
  dm <- c(0, diff(month))
  cdm <- cumsum(dm > 2)
  2016 - cdm
}

fixName <- function(name) {
  name <- gsub("*","",name, fixed=TRUE)
  name <- gsub(" (Tracking)", "", name, fixed=TRUE)
  name <- gsub("Mrng.", "Morning", name, fixed=TRUE)
  name <- name %>% str_replace_all("CBS News", "CBS") %>%
    str_replace_all("ABC News", "ABC") %>%
    str_replace_all("NY Times", "NYT") %>%
    str_replace_all("NBC News", "NBC") %>%
    str_replace_all("Wall St. Jrnl", "WSJ") %>%
    str_replace_all("Gravis Marketing", "Gravis") %>%
    str_replace_all("Suffolk University", "Suffolk") %>%
    str_replace_all("St. Anselm", "Saint Anselm") %>%
    str_replace_all("UMass Lowell", "UMass")
    
  name <- gsub("([A-Z][A-Z a-z()0-9]+)(.*)\\1", "\\1\\2", name)
  name <- gsub("([A-Z][A-Z a-z()0-9]+)(.*)\\1", "\\1\\2", name)
  splits <- strsplit(name, split="/") 
  sapply(splits, function(x) paste(unique(x),sep="/", collapse="/"))
}
###############
# show! 
rcp.gop <- "http://www.realclearpolitics.com/epolls/2016/president/nh/new_hampshire_republican_presidential_primary-3350.html#polls"

tables <- readHTMLTable(rcp.gop)
polls <- data.frame(tables[[4]])

pollsNA <- lapply(polls, sub)
write.csv(pollsNA, "temp.csv", row.names=FALSE)
polls <- read.csv("temp.csv")

polls$Poll <- fixName(polls$Poll)
dates <- strsplit(as.character(polls$Date), split=" - ")
d2 <- plyr::ldply(dates, function(x) data.frame(
  startDate = mdy(paste(x[1],"15", sep="/")),
  endDate = mdy(paste(x[2],"15", sep="/"))))
polls <- data.frame(polls, d2)
polls[1,]$endDate <- as.Date("2016/02/09")

year(polls$endDate) <- fixYear(polls$endDate)
year(polls$startDate) <- fixYear(polls$startDate)
polls$year <- year(polls$endDate)
polls$month <- month(polls$endDate)

samples <- strsplit(as.character(polls$Sample), split=" ")
s2 <- plyr::ldply(samples, function(x) data.frame(
  pollSize=suppressWarnings(as.numeric(x[1])),
  voterType=x[2]
))
#s2$voterType[is.na(s2$voterType)] <- polls$Sample[is.na(s2$voterType)]
#polls <- data.frame(polls, s2)
idx <- which(nchar(levels(polls$Poll)) %% 2 == 0)


mpolls <- melt(polls, measure.vars=5:12, na.rm=TRUE)
mpolls <- subset(mpolls, Poll != "RCP Average")


 lastPoll <- sprintf("Last Poll on %s", max(mpolls$endDate))
    cols <- c(brewer.pal(12, name="Paired"), "grey30", "grey50", "grey70", "grey80", "grey60", "black", "black", "black", "black", "black")
#    mpolls$voterType <- factor(mpolls$voterType, c("RV", "LV", "A"))
    
    p <- ggplot(aes(x=endDate, y=value, colour=Poll), data=subset(mpolls, (year >= 2016))) +
      caucuslayer(max(mpolls$value), party="R") +
      geom_smooth(aes(group=variable), colour="grey30", se=FALSE, size=.75) +
      geom_point(aes(x=endDate, y=value), size=2.5) + 
#      geom_segment(aes(x=endDate, xend=endDate, y=value-MoE, yend=value+MoE)) +
      scale_colour_manual(values=cols) + theme_bw() +
      theme(legend.position="bottom") + xlab("Date of Poll") + ylab("Percent") +
      facet_wrap(~variable) +
  #    scale_shape_manual("Type of Poll",values=c(19, 1, 4)) +
      ggtitle(lastPoll) +
      geom_point(aes(x=endDate, y=value), pch=1, size=4, data=subset(mpolls, Poll=="Final Results"))

   print(p)
```

```{r, echo=FALSE, fig.width=7.5, fig.height=5, message=FALSE, warning=FALSE}
rcp.dem <- "http://www.realclearpolitics.com/epolls/2016/president/nh/new_hampshire_democratic_presidential_primary-3351.html#polls"

tables <- readHTMLTable(rcp.dem)
polls <- data.frame(tables[[4]])

pollsNA <- lapply(polls, sub)
write.csv(pollsNA, "temp.csv", row.names=FALSE)
polls <- read.csv("temp.csv")

polls$Poll <- fixName(polls$Poll)
dates <- strsplit(as.character(polls$Date), split=" - ")
d2 <- plyr::ldply(dates, function(x) data.frame(
  startDate = mdy(paste(x[1],"16", sep="/")),
  endDate = mdy(paste(x[2],"16", sep="/"))))
polls <- data.frame(polls, d2)
polls[1,]$endDate <- as.Date("2016/02/09")

year(polls$endDate) <- fixYear(polls$endDate)
year(polls$startDate) <- fixYear(polls$startDate)
polls$year <- year(polls$endDate)
polls$month <- month(polls$endDate)

samples <- strsplit(as.character(polls$Sample), split=" ")
s2 <- plyr::ldply(samples, function(x) data.frame(
  pollSize=suppressWarnings(as.numeric(x[1])),
  voterType=x[2]
))
s2$voterType[is.na(s2$voterType)] <- polls$Sample[is.na(s2$voterType)]
polls <- data.frame(polls, s2)
idx <- which(nchar(levels(polls$Poll)) %% 2 == 0)


mpolls <- melt(polls, measure.vars=5:6, na.rm=TRUE)
mpolls <- subset(mpolls, Poll != "RCP Average")


 lastPoll <- sprintf("Last Poll on %s", max(mpolls$endDate))
    cols <- c(brewer.pal(12, name="Paired"), "grey30", "grey50", "grey70", "grey80", "grey60", "black", "black")
 #   mpolls$voterType <- factor(mpolls$voterType, c("LV", "RV", "A"))
    
    p <- ggplot(aes(x=endDate, y=value, colour=Poll), data=subset(mpolls, (year==2016))) +
      caucuslayer(max(mpolls$value), party="D") +
      geom_smooth(aes(group=variable), colour="grey30", se=FALSE, size=.75) +
      geom_point(aes(x=endDate, y=value), size=2.5) + 
 #     geom_segment(aes(x=endDate, xend=endDate, y=value-MoE, yend=value+MoE)) +
      scale_colour_manual(values=cols) + theme_bw() +
      theme(legend.position="bottom") + xlab("Date of Poll") + ylab("Percent") +
      facet_wrap(~variable) +
      scale_shape_manual("Type of Poll",values=c(19, 1, 4)) +
      ggtitle(lastPoll) +
      geom_point(aes(x=endDate, y=value), pch=1, size=4, data=subset(mpolls, Poll=="Final Results"))

    
   print(p)
```